### ISSUE TITLE
Nieogarnięty CSS w pilkaNozna.jsp

### ISSUE THREAD

**Issue by infexo37** [SyntaxErrorWMII/Kortowo-Reservations#6]
Na podstronie piłkaNożna.jsp jest nieogarnięty css. <br>
<b>_poprawić umiejscowienie SelectMenu i dodać header bar(odkomentować :P)<br>
<b>_dorobić fajny css do tabeli wyświetlającej terminy + jakiś button wybierający go :D

**Comment by mazurkiewiczadrian** [comment]
jutro się za to zabiorę
